### ISSUE TITLE
Rename nogil workers and builders?

### ISSUE THREAD

**Issue by itamaro** [python/buildmaster-config#398]
Based on @gpshead 's indication [here](https://discuss.python.org/t/nogil-installers-on-windows/34049/3?u=itamaro), I understand we want to avoid "nogil" as a public moniker, preferring the more wordy "free-threading".

I don't know how "public" we consider our buildbot configs, so I'm posing this as a question - I added a bunch of "nogil" flavored workers and builders - should I go ahead and rename them to "free-threading" everywhere?

**Comment by gpshead** [comment]
I don't have strong feelings about it on the buildbot names, sort of like the configure flag is already fine as `--disable-gil` - only devs see these.

conversations we have on discuss over topics feel "more public" than buildbot names and experimental configure flags.

**Comment by itamaro** [comment]
works for me :)

**Comment by vstinner** [comment]
Because of Python long history with "have a GIL", IMO "nogil" is a more obvious and clever name than "free-threading". At least, when we want a short name, like a tag/marker on a buildbot full name.

To advertize NoGIL feature, "free-threading" or "use all CPUs" or anything else would be better than "nogil".
